//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gym.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public customer()
        {
            this.accounts = new HashSet<account>();
        }
    
        public string customer_id { get; set; }
        public string customer_fullname { get; set; }
        public string customer_address { get; set; }
        public string customer_phone { get; set; }
        public string customer_photo { get; set; }
        public string customer_gender { get; set; }
        public System.DateTime customer_joindate { get; set; }
        public string trainer_id { get; set; }
        public string plan_id { get; set; }
        public string customer_username { get; set; }
        public string customer_password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<account> accounts { get; set; }
        public virtual plan plan { get; set; }
        public virtual trainer trainer { get; set; }
    }
}
