//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gym.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class equipment
    {
        public string equipment_id { get; set; }
        public string equipment_name { get; set; }
        public string equipment_quantity { get; set; }
        public int equipment_cost { get; set; }
        public string equipment_photo { get; set; }
    }
}
