//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gym.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Getaccount
    {
        public string account_id { get; set; }
        public string fee_paid { get; set; }
        public string plan_id { get; set; }
        public string plan_name { get; set; }
        public string customer_id { get; set; }
        public string customer_fullname { get; set; }
        public string fee_due { get; set; }
        public string total_fee { get; set; }
    }
}
