//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gym.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Getcustomer
    {
        public string customer_id { get; set; }
        public string customer_fullname { get; set; }
        public string plan_id { get; set; }
        public string plan_name { get; set; }
        public string trainer_id { get; set; }
        public string trainer_name { get; set; }
        public string customer_address { get; set; }
        public string customer_phone { get; set; }
        public string customer_photo { get; set; }
        public string customer_gender { get; set; }
        public System.DateTime customer_joindate { get; set; }
    }
}
